#server:
#  port: 8080
#  servlet:
#    context-path: /api
#
#spring :
#  application:
#    name: springboot-week03
#
#app:
#  app-name: 企业后台管理系统
#  version: 1.0.0
#  description: 基于 Spring Boot 3.5.11 构建
#  author:
#    name: mqxu
#    website: https://mqxu.top
#    email: 222222222@qq.com
#  features:
#    - 基于 Spring Boot 3.5.11 构建
#    - 集成 Spring Security
#    - 集成 Spring Data JPA
#    - 集成 Spring Boot Redis

spring:
  profiles:
    active: prod

